// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/tabbed/pqtype"
)

type LgGame struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	TypeID     uuid.NullUUID
	Datetime   time.Time
	Members    pqtype.NullRawMessage
	Location   pqtype.NullRawMessage
	Constrains pqtype.NullRawMessage
	Message    sql.NullString
	CreatedAt  interface{}
}

type LgGroup struct {
	ID        uuid.UUID
	Name      string
	Avatar    sql.NullString
	Members   json.RawMessage
	CreatedAt time.Time
}

type LgUser struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	Avatar    sql.NullString
	IsActive  bool
	CreatedAt interface{}
	Groups    []string
}
