// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateUser(ctx context.Context, id uuid.UUID) error
	CreateGame(ctx context.Context, arg CreateGameParams) (LgGame, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (LgGroup, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (LgUser, error)
	DeleteGame(ctx context.Context, id uuid.UUID) error
	DeleteGroup(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetGame(ctx context.Context, id uuid.UUID) (LgGame, error)
	GetGroup(ctx context.Context, id uuid.UUID) (LgGroup, error)
	GetUser(ctx context.Context, id uuid.UUID) (LgUser, error)
	InactivateUser(ctx context.Context, id uuid.UUID) error
	ListGames(ctx context.Context, arg ListGamesParams) ([]LgGame, error)
	ListGroups(ctx context.Context, arg ListGroupsParams) ([]LgGroup, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]LgUser, error)
	UpdateGame(ctx context.Context, arg UpdateGameParams) (LgGame, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (LgGroup, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (LgUser, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
